### ISSUE TITLE
Bundle functions individually

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/displace#33]
[Optimization / Individual packaging per function](https://github.com/serverless-heaven/serverless-webpack#optimization--individual-packaging-per-function)

```yml
# serverless.yml
...
package:
  individually: true
...
```
